End poitn listar usuarios
RolandoGO/grupo-n-1 pull request #6
Opened 2022-12-08 21:05 UTC by RolandoGO

## Jira Ticket

- [INSERT NAME HERE](INSERT LINK HERE)

## Description
AS:
I Want:
To:

## Evidence:
(Put screenshots/video/gifs here)

2022-12-08 21:07 UTC, sofiapel approved these changes

2022-12-09 14:20 UTC, gabodmc requested changes
Esta todo muy bien, solo un comentario

2022-12-12 00:47 UTC, sofiapel approved these changes

2022-12-12 17:53 UTC, gabodmc approved these changes

2022-12-12 20:34 UTC, merged