Getting user data
RolandoGO/grupo-n-1 pull request #7
Opened 2022-12-08 22:43 UTC by RolandoGO

service and controller to get one user data

## Evidence:
(Put screenshots/video/gifs here)

2022-12-09 14:22 UTC, gabodmc requested changes
Solo un pequeño comentario

2022-12-11 22:48 UTC, RolandoGO commented
> Solo un pequeño comentario

agregue mas comentarios al codigo.

2022-12-12 17:52 UTC, gabodmc approved these changes

2022-12-13 01:05 UTC, sofiapel approved these changes

2022-12-13 14:32 UTC, merged